### ISSUE TITLE
Github actionsで自動rubocopを実行

### ISSUE THREAD

**Issue by yusukedayo** [morning-study-party/hatsunetsu-kun#31]
インデントのずれでレビューが止まるの勿体無いと思ったのでpushでrubocopが自動実行される機能を実装したい。
[RailsにGitHub Actionsの導入（Rspec, Rubocop）](https://zenn.dev/ryouzi/articles/cd6857c08e60e7)

**Comment by yusukedayo** [comment]
これを追加したら良さそう
```
name: Run rubocop

on:
  push:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop
```
